version: 2

jobs:
  build:
    working_directory: ~/electron-crash-report-server
    docker:
      - image: circleci/ruby:2.4.2
        environment:
        - PG_HOST=localhost
        - PG_USER=ubuntu
        - RACK_ENV=test
      - image: circleci/postgres:9.6-alpine
        environment:
        - POSTGRES_USER=ubuntu
        - POSTGRES_DB=electron_crash_report_server_test
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "Gemfile" }}
      - run:
          name: bundle install
          command: bundle install --path vendor/bundle
      - run:
          name: database setup
          command: |
            sleep 1
            bin/sequel -m migrate/ $DATABASE_URL
          environment:
            DATABASE_URL: "postgres://ubuntu@localhost:5432/electron_crash_report_server_test"
      - run:
          name: rake test
          command: bin/rake test
          environment:
            AUTH_USER: crash
            AUTH_PASS: electron
            DATABASE_URL: "postgres://ubuntu@localhost:5432/electron_crash_report_server_test"
            SESSION_SECRET: secret
      - run:
          name: rake rubocop
          command: bin/rake rubocop
      - save_cache:
          key: dependency-cache-{{ checksum "Gemfile" }}
          paths:
            - ./vendor/bundle
